### ISSUE TITLE
Training Issue 

### ISSUE THREAD

**Issue by deeplearning987** [Prateek93a/DoodleAI#1]
Hello Team,
I'm trying to train the Doodle AI Classifier Model but I'm facing the issue while training it.(Optimizer error)Can you please update the complete code in github.And there's an issue in flask app as well.As it is asking me to load the model.
![Screenshot (23)](https://user-images.githubusercontent.com/89828183/133963445-1c384d07-e444-4957-b051-818f3c651fb6.png)
![Screenshot (24)](https://user-images.githubusercontent.com/89828183/133963478-f323a011-5796-4f5b-b5b9-75d2f967e911.png)

**Comment by Prateek93a** [comment]
@deeplearning987 I have updated the notebook. You can check it. For the app, you need to make sure the model is loaded before you can actually start using it.

**Comment by deeplearning987** [comment]
hello @Prateek93a how to load the model in flask app? Actually I'm running the app.py file as you've already trained the onnx_model.onnx which is model folder. Can you mention the steps?
