### ISSUE TITLE
Flask Code 

### ISSUE THREAD

**Issue by deeplearning987** [Prateek93a/DoodleAI#2]
Hello @Prateek93a 
How to combine the trained model with Flask API. When I run the app.py file. It is displaying the front-end web page but it's saying you need to load the model. As you've already kept the trained model I thought it would run similar to your app running in Heroku. But the output is not the same. Can you please help on where to load the model in flask app?

**Comment by Prateek93a** [comment]
Change the base url accordingly: https://github.com/Prateek93a/DoodleAI/blob/3d5bb58063309f48578dc6fc31c3c576cd540ee4/static/js/index.js#L5

In your case, leave it as empty string or your localhost url.
