### ISSUE TITLE
Running Flask on Local Environment not on Heroku Platform

### ISSUE THREAD

**Issue by deeplearning987** [Prateek93a/DoodleAI#3]
Hello @Prateek93a 
I'm trying to run app.py file (FLASK FILE) but it is showing you need to load the model first.

I'm running these two commands.

set FLASK_APP = app.py

flask run 

The model which deployed on Heroku is working fine.But when i'm trying to run on the local environment
 the app.py file it is showing error mentioned below.I also changed my local model path but it is not working in index.js file.Can you please help.

await sess.loadModel(baseUrl + "C:\\Users\\deeplearing\\Downloads\\DoodleAI-master (1)\\DoodleAI-master\\static\\model\\onnx_model.onnx");

The first picture shows you need to load the model while.You can see the URL.

The Second Picture is the App Hosted on Heroku Platform

![Screenshot (25)](https://user-images.githubusercontent.com/89828183/134103866-f4f84b97-1d93-40d5-8d3d-7c1906ecbe25.png)
![Screenshot (26)](https://user-images.githubusercontent.com/89828183/134103877-076452dc-f33c-4744-a642-7d6d6aab4f08.png)
![Screenshot (27)](https://user-images.githubusercontent.com/89828183/134105238-3df712a3-5537-449a-86b4-7d825d05c27f.png)

**Comment by Prateek93a** [comment]
await sess.loadModel( "http://127.0.0.1:5000/static/model/onnx_model.onnx");

**Comment by deeplearning987** [comment]
Hello @Prateek93a 

Still the same  error. 

<img width="957" alt="model-saving" src="https://user-images.githubusercontent.com/89828183/134122679-503887b0-9ff4-4e80-ad88-4434d669636d.PNG">

![Screenshot (30)](https://user-images.githubusercontent.com/89828183/134122353-6c3c0026-9ffb-4802-bfbb-ce7311067987.png)
